export const reduxActionTypes = {
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
  LOADING: "LOADING",
  ERROR: "ERROR",
  IN_STOCK: "IN_STOCK",
  TOGGLE_BRANDS: "TOGGLE_BRANDS",
};
